# Generated by Django 6.0.5 on 2026-05-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('nct_id', models.CharField(help_text='Trial identifier ', max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrialVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('version_date', models.DateField()),
                ('recruitment_status', models.CharField(max_length=100)),
                ('enrollment', models.IntegerField(blank=True, null=True)),
                ('sponsors', models.JSONField(default=list)),
                ('conditions_module', models.JSONField(default=list)),
                ('primary_outcome', models.JSONField(default=list)),
                ('study_phase', models.JSONField(default=list)),
                ('locations', models.JSONField(default=list)),
                ('investigators', models.JSONField(default=dict)),
                ('eligibility_criteria', models.JSONField(default=dict)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='scraper.trial')),
            ],
            options={
                'ordering': ['trial', 'version_number'],
                'unique_together': {('trial', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='TrialChangeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_payload', models.JSONField(default=dict, help_text='Structured JSON representing the exact fields changed')),
                ('status_changed', models.BooleanField(default=False, help_text='Recruitment status changed [cite: 43]')),
                ('enrollment_updated', models.BooleanField(default=False, help_text='Enrollment updated [cite: 44]')),
                ('sites_changed', models.BooleanField(default=False, help_text='Trial site added and removed [cite: 45]')),
                ('eligibility_modified', models.BooleanField(default=False, help_text='Eligibility modified [cite: 46]')),
                ('outcomes_changed', models.BooleanField(default=False, help_text='Outcome measures changed [cite: 47]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='scraper.trial')),
                ('from_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_from', to='scraper.trialversion')),
                ('to_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_to', to='scraper.trialversion')),
            ],
            options={
                'ordering': ['-to_version__version_date'],
            },
        ),
        migrations.CreateModel(
            name='RawTrialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('version_date', models.DateField(blank=True, null=True)),
                ('full_api_payload', models.JSONField(help_text='The complete, unmodified JSON dictionary returned by the API')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_responses', to='scraper.trial')),
            ],
            options={
                'unique_together': {('trial', 'version_number')},
            },
        ),
    ]
