# Generated by Django 6.0.5 on 2026-05-12 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialVersionPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=20)),
                ('json_path', models.CharField(max_length=255)),
                ('change_value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_from', to='scraper.trialversion')),
                ('to_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_to', to='scraper.trialversion')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='scraper.trial')),
            ],
            options={
                'ordering': ['-to_version__version_date'],
            },
        ),
        migrations.DeleteModel(
            name='TrialChangeSummary',
        ),
    ]
