# Generated by Django 6.0.5 on 2026-05-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_trialversionpatch_delete_trialchangesummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trialversionpatch',
            options={},
        ),
        migrations.AlterField(
            model_name='trialversionpatch',
            name='from_version',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trialversionpatch',
            name='to_version',
            field=models.IntegerField(),
        ),
    ]
