# Generated by Django 6.0.5 on 2026-05-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_trialversionpatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialversionpatch',
            name='value',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='trialversionpatch',
            name='change_value',
            field=models.JSONField(null=True),
        ),
    ]
